---
model_params:
  model_dir: "EarthBytePlateMotionModel-ARCHIVE/Global_Model_WD_Internal_Release_2019_v2_Clennett_NE_Pacific"
  min_time: 0
  max_time: 170
  model_export_dir: "export"
  rotation_filenames:
    - "Alps_Mesh_Rotations.rot"
    - "Andes_Flat_Slabs_Rotations.rot"
    - "Andes_Rotations.rot"
    - "Australia_Antarctica_Mesh_Rotations.rot"
    - "Australia_North_Zealandia_Rotations.rot"
    - "Clennett_2020_Rotations.rot"
    - "Eurasia_Arabia_Mesh_Rotations.rot"
    - "Global_250-0Ma_Rotations.rot"
    - "North_America_Flat_Slabs_Rotations.rot"
    - "North_America_Mesh_Rotations.rot"
    - "North_China_Mesh_Rotations.rot"
    - "South_Atlantic_Rotations.rot"
    - "South_China_DeformingModel.rot"
    - "Southeast_Asia_Rotations.rot"
  topology_filenames:
    - "Alps_Deforming_Mesh.gpml"
    - "Alps_Mesh_Topologies.gpml"
    - "America_Anyui_Deforming_Mesh.gpml"
    - "America_Anyui_Mesh_Topologies.gpml"
    - "Andes_Deforming_Mesh.gpml"
    - "Andes_Flat_Slabs_Topologies.gpml"
    - "Andes_Mesh_Topologies.gpml"
    - "Arctic_Eurasia_Deforming_Mesh.gpml"
    - "Arctic_Eurasia_Mesh_Topologies.gpml"
    - "Australia_Antarctica_Deforming_Mesh.gpml"
    - "Australia_Antarctica_Mesh_Topologies.gpml"
    - "Australia_North_Zealandia_Deforming_Mesh.gpml"
    - "Australia_North_Zealandia_Mesh_Topologies.gpml"
    - "Baja_Deforming_Mesh.gpml"
    - "Clennett_2020_NAm_boundaries.gpml"
    - "Clennett_2020_Plates.gpml"
    - "Coral_Sea_Deforming_Mesh.gpml"
    - "Coral_Sea_Topologies.gpml"
    - "East-West_Gondwana_Deforming_Mesh_and_Topologies.gpml"
    - "East_African_Rift_Deforming_Mesh_and_Topologies.gpml"
    - "Ellesmere__Deforming_Mesh.gpml"
    - "Eurasia_Arabia_Deforming_Mesh_and_Topologies.gpml"
    - "Global_Paleozoic_PlateBoundaries.gpml"
    - "Greater_India_Deforming_Mesh.gpml"
    - "Greater_India_Mesh_Topologies.gpml"
    - "North_America_Mesh_Topologies.gpml"
    - "North_Atlantic_Deforming_Mesh.gpml"
    - "North_Atlantic_Mesh_Topologies.gpml"
    - "North_China_Deforming_Mesh.gpml"
    - "North_China_Mesh_Topologies.gpml"
    - "Northern_Andes_Deforming_Mesh.gpml"
    - "Northern_Andes_Mesh_Topologies.gpml"
    - "Papua_New_Guinea_Deforming_Meshes.gpml"
    - "Papua_New_Guinea_Mesh_Topologies.gpml"
    - "Scotia_Deforming_Mesh_and_Topologies.gpml"
    - "Siberia_Eurasia_Deforming_Mesh.gpml"
    - "Siberia_Eurasia_Mesh_Topologies.gpml"
    - "South_Atlantic_Deforming_Mesh.gpml"
    - "South_Atlantic_Mesh_Topologies.gpml"
    - "South_China_Mesh_Topologies.gpml"
    - "South_China_Sea_Deforming_Mesh.gpml"
    - "South_Zealandia_Deforming_Mesh.gpml"
    - "South_Zealandia_Mesh_Topologies.gpml"
    - "Southeast_Asia_Deforming_Mesh.gpml"
    - "Southeast_Asia_Mesh_Topologies.gpml"
    - "West_Antarctic_Zealandia_Deforming_Mesh.gpml"
    - "West_Antarctica_Zealandia_Mesh_Topologies.gpml"
    - "Western_North_America_Deforming_Mesh.gpml"
    - "Western_Tethys_Deforming_Mesh.gpml"
    - "Western_Tethys_Tectonic_Boundary_Topologies.gpml"
  coastline_filenames:
    - "Clennett_2020_Coastlines.gpml"
    - "Clennett_2020_Terranes.gpml"
    - "South_America.gpml"
raster_data:
  agegrid_dir: "Clennett_data/AgeGrids/masked"
  sedthick_dir: "Clennett_data/SedimentThickness"
  carbonate_dir: "Clennett_data/CarbonateThickness/uncompacted"
run_params:
  output_filename: "subduction_data_Clennett.csv"
  nprocs: 8
  verbose: True
