---
model_params:
  model_dir: "EarthBytePlateMotionModel-ARCHIVE/Merdith_etal_2021_Published"
  min_time: 0
  max_time: 1000
  model_export_dir: "export"
  rotation_filenames:
    - "1000_0_rotfile_Merdith_et_al.rot"
  topology_filenames:
    - "250-0_plate_boundaries_Merdith_et_al.gpml"
    - "410-250_plate_boundaries_Merdith_et_al.gpml"
    - "1000-410-Convergence_Merdith_et_al.gpml"
    - "1000-410-Divergence_Merdith_et_al.gpml"
    - "1000-410-Topologies_Merdith_et_al.gpml"
    - "1000-410-Transforms_Merdith_et_al.gpml"
    - "TopologyBuildingBlocks_Merdith_et_al.gpml"
  coastline_filenames:
    - "shapes_coastlines_Merdith_et_al.gpml"
    - "shapes_continents_Merdith_et_al.gpml"
    - "shapes_cratons_Merdith_et_al.gpml"
run_params:
  output_filename: "subduction_data_Merdith.csv"
  nprocs: 8
  verbose: True
